### PR TITLE
Listview

### PR DESCRIPTION
**Pull request by bsonge**
Adding listview in reference to #43

### CODE REVIEW

**Review by Quinn-Donnelly — APPROVED** [review]
I think this is a good start. Obviously we need tests for it but can wait until it's done being fully implemented given other priorities. @wrejcodes can help in styling it with bootstrap. The backend now has a basic search that can be used to test it once @Justinnunez1717 writes the sagas for said route.

**Comment by wrejcodes** [comment]
Yeah it was kind of a weird spot because I wanted to get his changes so we could work on adding bootstrap and just wanted to get bootstrap in the project itself. But now I’m thinking I probably just should have forked his repo instead of him making s pull request here. It was more of I wanted to get all the pending progress so that we can knock things out. Before we merge should I just fork his and work on his copy that way or do you think this is okay for now and we get bootstrap added to the main repository and start styling everything?

**Comment by wrejcodes** [comment]
Also sorry for the ramble ahead of time. Literally just woke up and on my phone lol

**Comment by Quinn-Donnelly** [comment]
Just for the future @wrejcodes and @bsonge, the way to accomplish that with this design is to do 
```
git remote add brayden <his git url>
```
then you can
```
git fetch
```
and then 
```
git checkout brayden <his branch>
```

**Comment by wrejcodes** [comment]
Yup. That’s totally what we should have done. Makes much more sense.

**Comment by Quinn-Donnelly** [comment]
I think if you add the remote and push to his branch (Note that he will have to add you as a collaborator on his local repo) then this PR will be updated with your changes and we can merge from that. If you have already done the fork way then continue with that. What ever makes these changes get finished and on the front end as quickly as possible is the route we should take.

**Comment by bsonge** [comment]
An improved version has been created that addresses the same issue.

**Pull request closed without merging**
